# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.18.4

# Mod Properties
mod_version = 1.4.2
maven_group = nordmods
archives_base_name = primitive_multipart_entities

# Dependencies
fabric_version=0.154.0+26.1.2
